### ISSUE TITLE
Incorrect indentation on nested function calls

### ISSUE THREAD

**Issue by hdante** [rust-lang/rust.vim#466] opened 2021-12-30 02:40 UTC
* rust.vim version: 

vim 8.2.3890
rust.vim: 2017 Jun 13

My .vimrc file:

    filetype plugin indent on

No .vim directory

Steps to reproduce:

    fn double(x: u32) -> u32 {
        2*x
    }

    fn p(a: u32, b: u32, c: u32, d: u32) {
        println!("{} {} {} {}", a, b, c, d)
    }

    fn main() {
        p(1, double(2),
        3, 4);

        p(double(5), 6,
        7, 8);

        p (9, 10,
           double(11), 12);
    }

Type the above program and indent whole file with the = command.

Expected vs. actual behavior:

Expected indentation:

    fn double(x: u32) -> u32 {
        2*x
    }

    fn p(a: u32, b: u32, c: u32, d: u32) {
        println!("{} {} {} {}", a, b, c, d)
    }

    fn main() {
        p(1, double(2),
          3, 4);

        p(double(5), 6,
          7, 8);

        p (9, 10,
           double(11), 12);
    }

Actual indentation: lines 11 and 14 (continuation lines of first and second function calls) have incorrect indentation.

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

Commands do not exist.

**Comment by chris-morgan** [comment] 2022-01-06 01:21
Duplicate of #77. Probably difficult to solve, and not considered particularly important since it’s a style that never arises with the standard rustfmt style which most people use.

**Closed by chris-morgan** 2022-01-06 01:21 UTC
