### ISSUE TITLE
Highlight struct names in `rustFoldBraces`

### ISSUE THREAD

**Issue by Iron-E** [rust-lang/rust.vim#429] opened 2020-12-10 03:22 UTC
Hello! Thank you guys for your work on Rust– let alone this project.

There is one small oddity with the highlighting I've noticed, however: mainly, that `struct` names are not highlighted when used as a `struct` field. These are typically located inside the `rustFoldBraces` region.

For example:

```rust
struct Foo
{
    foo: Bar
}
struct Bar {…}
```

The `Bar` in `foo: Bar` should be highlighted the same as `Foo` in `struct Foo`. Right now `rustIdentifier` is used for `Foo` but not for `Bar` .

It seems that primitives are detected though:

```rust
struct Bar
{
    bar: u8
}
```

**Comment by chris-morgan** [comment] 2020-12-10 09:05
I’m afraid this has been a deliberate decision: you *can’t* correctly highlight types in all places without a more detailed parser than is possible in Vimscript (or desirable—syntax highlighting can get pretty slow when you go too detailed; and it’s already slower than I’d like in some places), so we’ve preferred to highlight none, except for primitive and prelude types (which is itself slightly controversial, see [issues matching “prelude”](https://github.com/rust-lang/rust.vim/issues?q=prelude)).

This is also actually a duplicate of https://github.com/rust-lang/rust.vim/issues/142, so I’m closing it in favour of that.

**Closed by chris-morgan** 2020-12-10 09:05 UTC
