### ISSUE TITLE
Can't find directory "src" in cdpath when use `:make build`

### ISSUE THREAD

**Issue by VMatrix1900** [rust-lang/rust.vim#230] opened 2018-07-06 13:30 UTC
* rust.vim version: 
I use `vim-plug` to install latest rust.vim master

Steps to reproduce:

1. Open a rust source file in src folder
2. run `:compiler cargo`
3. run `:make build`

Expected vs. actual behavior:
Expected: run cargo build and pop the location list for errors.

Actual behavior:
```
Error detected while processing BufEnter Auto commands for "*":
E344: Can't find directory "src" in cdpath
E472: Command failed
```

Paste debugging info from the Rust Vim plugin via _one_ of the following
commands: `:RustInfo`,  `:RustInfoToClipboard`, or `:RustInfoToFile <filename>`.

```
rust.vim Global Variables:

let g:ftplugin_rust_source_path = v:null
let g:loaded_syntastic_rust_cargo_checker = v:null
let g:loaded_syntastic_rust_filetype = v:null
let g:loaded_syntastic_rust_rustc_checker = v:null
let g:rust_bang_comment_leader = v:null
let g:rust_cargo_avoid_whole_workspace = v:null
let g:rust_clip_command = v:null
let g:rust_conceal = v:null
let g:rust_conceal_mod_path = v:null
let g:rust_conceal_pub = v:null
let g:rust_fold = v:null
let g:rust_last_args = v:null
let b:rust_last_args = []
let g:rust_last_rustc_args = v:null
let b:rust_last_rustc_args = []
let g:rust_original_delimitMate_excluded_regions = v:null
let g:rust_playpen_url = v:null
let g:rust_recent_nearest_cargo_tol = v:null
let g:rust_recent_root_cargo_toml = v:null
let g:rust_recommended_style = v:null
let g:rust_set_conceallevel = v:null
let g:rust_set_conceallevel=1 = v:null
let g:rust_set_foldmethod = v:null
let g:rust_set_foldmethod=1 = v:null
let g:rust_shortener_url = v:null
let g:rustc_makeprg_no_percent = v:null
let g:rustc_path = v:null
let g:rustfmt_autosave = 0
let g:rustfmt_autosave_because_of_config = v:null
let g:rustfmt_autosave_if_config_present = v:null
let g:rustfmt_command = 'rustfmt'
let g:rustfmt_emit_files = 0
let g:rustfmt_fail_silently = 0
let g:rustfmt_options = ''
let g:syntastic_extra_filetypes = ['rust']
let g:syntastic_rust_cargo_fname = v:null
error: toolchain 'stable-x86_64-apple-darwin' does not have the binary `rustfmt`

rustc 1.27.0 (3eda71b00 2018-06-19)

cargo 1.27.0 (1e95190e5 2018-05-27)


NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```

**Comment by da-x** [comment] 2018-07-06 14:02
Thanks for reporting an issue!

I was not able to reproduce this - I tried to duplicate your setup - Neovim v0.3.0 and a very minimal configuration with vim-plug.

Are you sure it's not some other plugin causing problems? Or an unusual `cdpath` setting? We don't have a `BufEnter` autocmd in `rust.vim`, but the error message you are getting indicates a hook from such an `autocmd`. Maybe you have some old hook code laying around in your config?

**Comment by VMatrix1900** [comment] 2018-07-06 15:12
@da-x Thanks for your reply. I find the problem. I use the [spf13-vim](https://github.com/spf13/spf13-vim) config. It has a setting to automatically switch to the current file directory when a new buffer is opened, see [vimrc](https://github.com/spf13/spf13-vim/blob/3.0/.vimrc#L115-L122)

So I removed those lines. Then the `BufEnter` error is gone. But I get another error:
```
"src/main.rs" [New file] --No lines in buffer--
(1 of 90) error 433: failed to resolve. Use of undeclared type or module `Either
```
And a new buffer named main.rs is created.

**Comment by da-x** [comment] 2018-07-06 15:22
Seems that cargo is building something, because of the error received about trying to resolve an `Either::` path. Probably from the build of the crate? Maybe this new empty `src/main.rs` is not the actual `main.rs` you are trying to open. Can you do `:echo getcwd()` while in buffer of the the empty `main.rs` to see where Vim is trying to open it?

**Comment by da-x** [comment] 2018-07-06 16:02
If you write it with `:w!`, does it truncate the `src/main.rs` file?  (back it up first :).

**Comment by VMatrix1900** [comment] 2018-07-06 16:09
Can not write it with `:w!`. Error is:
```
"src/main.rs"
E212: Can't open file for writing: no such file or directory
```

**Comment by da-x** [comment] 2018-07-06 16:15
I think it tries opening `src/src/main.rs` for writing (you can confirm by creating `src/src`) and see if the write succeeds.

**Comment by VMatrix1900** [comment] 2018-07-06 16:17
Yes, you are right. After I create `src/src` it writes the empty `src/src/main.rs`.

**Comment by VMatrix1900** [comment] 2018-07-06 16:53
Yes. It works.

**Comment by VMatrix1900** [comment] 2018-07-07 03:33
@da-x So, each time I run make I need to change dir to crate root library?

**Comment by da-x** [comment] 2018-07-07 06:59
I pushed a fix, please try it out.

**Closed** 2018-07-07 06:58 UTC

**Comment by VMatrix1900** [comment] 2018-07-07 07:16
The fix works out. Thank you very much
